application: panelr
version: 3
runtime: python
api_version: 1

handlers:
- url: /favicon.ico
  static_files: static/icons/favicon.ico
  upload: static/icons/favicon.ico
- url: /static
  static_dir: static
- url: /([\w\.]+)/panel/.*
  script: panel.py
- url: /([\w\.]+)/services/.*
  script: services.py
- url: /.*
  script: main.py
  
